manifest:
  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: mcuboot-repo
      url-base: https://github.com/JuulLabs-OSS/

  projects:
    - name: zephyr
      revision: v2.3.0
      import: true
